# Collections Requirements for FQCN Support
# This file defines the Ansible collections required for FQCN module usage
# Install with: ansible-galaxy collection install -r collections/requirements.yml

collections:
  # Core community collections
  - name: community.general
    version: ">=8.0.0"
    source: https://galaxy.ansible.com
  
  - name: community.mysql
    version: ">=3.8.0"
    source: https://galaxy.ansible.com
  
  - name: community.postgresql
    version: ">=3.4.0"
    source: https://galaxy.ansible.com
  
  - name: community.mongodb
    version: ">=1.6.0"
    source: https://galaxy.ansible.com
  
  - name: community.docker
    version: ">=3.4.0"
    source: https://galaxy.ansible.com
  
  - name: ansible.posix
    version: ">=1.5.0"
    source: https://galaxy.ansible.com
  
  - name: ansible.windows
    version: ">=2.0.0"
    source: https://galaxy.ansible.com
  
  # Additional collections for specific use cases
  - name: community.crypto
    version: ">=2.15.0"
    source: https://galaxy.ansible.com
  
  - name: community.dns
    version: ">=2.6.0"
    source: https://galaxy.ansible.com
  
  - name: community.network
    version: ">=5.0.0"
    source: https://galaxy.ansible.com
  
  - name: community.vmware
    version: ">=4.0.0"
    source: https://galaxy.ansible.com
  
  # System-specific collections
  - name: community.libvirt
    version: ">=1.3.0"
    source: https://galaxy.ansible.com
  
  - name: community.proxmox
    version: ">=1.0.0"
    source: https://galaxy.ansible.com