name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us understand and reproduce the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting your bug report
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported already
          required: true
        - label: I have read the documentation and troubleshooting guide
          required: true
        - label: I am using a supported version of FQCN Converter
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug you encountered...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the bug
      placeholder: |
        1. Run command: `fqcn-converter convert playbook.yml`
        2. With input file containing: ...
        3. Expected: ...
        4. Actual: ...
    validations:
      required: true

  - type: textarea
    id: sample-files
    attributes:
      label: Sample Files
      description: If applicable, provide sample Ansible files that demonstrate the issue
      placeholder: |
        ```yaml
        # playbook.yml
        - name: Example playbook
          hosts: localhost
          tasks:
            - name: Create user
              user:
                name: testuser
        ```

  - type: input
    id: fqcn-version
    attributes:
      label: FQCN Converter Version
      description: What version of FQCN Converter are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "3.9.0"
    validations:
      required: true

  - type: input
    id: ansible-version
    attributes:
      label: Ansible Version
      description: What version of Ansible are you using?
      placeholder: "ansible-core 2.14.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other (please specify in additional context)
    validations:
      required: true

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: If applicable, provide the complete error output or stack trace
      placeholder: |
        ```
        Paste error output here...
        ```
      render: shell

  - type: textarea
    id: logs
    attributes:
      label: Log Output
      description: If applicable, provide relevant log output (use --verbose or --debug flags)
      placeholder: |
        ```
        Paste log output here...
        ```
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Custom configuration files used
        - Specific Ansible collections involved
        - Network environment details
        - Any workarounds you've tried

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing a fix?
      options:
        - label: I would be willing to submit a pull request to fix this issue
          required: false