blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/ansible-fqcn-converter/ansible-fqcn-converter/blob/main/README.md
    about: Read the project documentation and usage guides
  - name: 💬 GitHub Discussions
    url: https://github.com/ansible-fqcn-converter/ansible-fqcn-converter/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: https://github.com/ansible-fqcn-converter/ansible-fqcn-converter/security
    about: Report security vulnerabilities privately