name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide detailed information about your request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting your feature request
      options:
        - label: I have searched existing issues and discussions to ensure this feature hasn't been requested already
          required: true
        - label: I have read the project roadmap and documentation
          required: true
        - label: This feature aligns with the project's goals and scope
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: |
        Describe the problem or limitation you're experiencing...
        
        Example: "When converting large Ansible projects, I need to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: |
        Describe how you envision this feature working...
        
        Example: "Add a new CLI flag --parallel-workers that allows..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: |
        Describe any alternative solutions you've considered...
        
        Example: "I also considered using configuration files, but..."

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - CLI Enhancement
        - API Enhancement
        - Performance Improvement
        - New Conversion Feature
        - Configuration Option
        - Documentation Improvement
        - Developer Tool
        - Other (please specify below)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Blocking my use case
        - Critical - Essential for adoption
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific use cases where this feature would be beneficial
      placeholder: |
        1. Use case 1: When working with...
        2. Use case 2: In environments where...
        3. Use case 3: For teams that need to...
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide concrete examples of how this feature would work
      placeholder: |
        Example CLI usage:
        ```bash
        fqcn-converter convert --new-feature-flag playbook.yml
        ```
        
        Example API usage:
        ```python
        converter = FQCNConverter(new_feature=True)
        result = converter.convert_file("playbook.yml")
        ```

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What would need to be implemented for this feature to be considered complete?
      placeholder: |
        - [ ] Feature works with CLI interface
        - [ ] Feature works with Python API
        - [ ] Documentation is updated
        - [ ] Tests are added
        - [ ] Backward compatibility is maintained

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: What impact would this feature have on existing functionality?
      placeholder: |
        Consider:
        - Breaking changes (if any)
        - Performance implications
        - Compatibility with existing features
        - Documentation updates needed

  - type: input
    id: target-version
    attributes:
      label: Target Version
      description: What version would you like to see this feature in?
      placeholder: "0.2.0"

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request
      placeholder: |
        - Links to relevant documentation
        - Screenshots or mockups
        - References to similar features in other tools
        - Community discussions or feedback

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing this feature?
      options:
        - label: I would be willing to submit a pull request to implement this feature
          required: false
        - label: I would be willing to help with testing this feature
          required: false
        - label: I would be willing to help with documentation for this feature
          required: false

  - type: checkboxes
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Does this feature require breaking changes?
      options:
        - label: This feature may require breaking changes to existing APIs
          required: false
        - label: This feature can be implemented without breaking existing functionality
          required: false